version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: education_db
    environment:
      POSTGRES_DB: education_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  liquibase:
    image: liquibase/liquibase:4.23
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./liquibase:/liquibase/changelog
    command: >
      --changelog-file=master.xml
      --url=jdbc:postgresql://postgres:5432/education_db
      --username=postgres
      --password=postgres
      update

  profile-microservice:
    build:
      dockerfile: profile/Dockerfile
    container_name: education_profile
    depends_on:
      liquibase:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/education_db
    command: uvicorn main:app --host 0.0.0.0 --reload

volumes:
  postgres_data: